#! /bin/bash
# blltrx sway config file

### Misc

# enable numlock by default
input type:keyboard xkb_numlock enabled

# disabling titlebar
default_border none
default_floating_border none
font pango:monospace 10
titlebar_padding 1
titlebar_border_thickness 0

# adding gaps
gaps inner 5px
# gaps outer 5px


### Variables

# Use Mod1 for alt
# Use Mod4 for win/super
set $mod Mod4

set $left h
set $down j
set $up k
set $right l
set $term kitty
set $menu fuzzel -I 
set $lockscreen exec swaylock

# vnc passthrough mode
mode passthrough {
	bindsym $mod+Pause mode default
}
bindsym $mod+Pause mode passthrough


### Output configuration

output * {
    scale 1
    bg ~/.config/wallpapers/arch.png fill
}

# laptop screen
output "BOE 0x0BCA Unknown" { 
      scale 1.4
      res 2256x1504
      pos 0 0
}

# home monitor
output 'Dell Inc. DELL U2414H 292K471U0HCL' { 
    scale 1
    res 1920x1080
    pos 1611 0
}

# sit
output 'HKC OVERSEAS LIMITED 24N1A 0000000000001' res 1920x1080 pos -1920 0

# laidlaw monitors
output 'Dell Inc. DELL U3223QE GMY7J04' scale 1.5 res 3840x2160
output 'Dell Inc. DELL U3223QE FPY7J04' scale 1.5 res 3840x2160


### Input configuration

input * {
    xkb_layout "gb"
}

input "type:mouse" {
  accel_profile flat
} 

input "type:touchpad" {
  natural_scroll enabled
  scroll_factor 0.4
  pointer_accel 0.2
  middle_emulation enabled
  tap enabled
  accel_profile adaptive
  # dwt disabled
}


### Key bindings

# Basics:
    bindsym $mod+Return exec $term
    bindsym $mod+Shift+q kill
    bindsym $mod+d exec $menu
    floating_modifier $mod normal
    bindsym $mod+Shift+c reload
    bindsym $mod+Shift+e exec swaynag -m "exit sway?" -b "yes" "swaymsg exit"

    # multimedia keybindings 
        # volume keys
        bindsym XF86AudioMute exec pactl set-sink-mute @DEFAULT_SINK@ toggle
        bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -5%
        bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5%

        # media key function
        bindsym XF86AudioPlay exec playerctl play-pause
        bindsym XF86AudioNext exec playerctl next
        bindsym XF86AudioPrev exec playerctl previous

    # brightness keys
    bindsym XF86MonBrightnessDown exec light -U 5
    bindsym XF86MonBrightnessUp exec light -A 5

    # lockscreen
    bindsym $mod+n exec $lockscreen

    # suspend
    bindsym $mod+XF86AudioMedia exec systemctl suspend

    # screenshot
    bindsym Print exec grim $HOME/Documents/photos/screenshots/$(date -Iseconds).png && notify-send "grim > screenshot taken" "stored at ~/Documents/photos/screenshots/"    

    bindsym $mod+c exec slurp | grim -g - - | wl-copy -t image/png && notify-send "grim > screenshot taken" "stored in clipboard"

    # bindsym $mod+m exec grimfilepath=$HOME/Documents/notes/physics22/attach/$(zenity --entry --title="enter file name" --text="all screenshots will be saved as .png").png && slurp | grim -g - $grimfilepath

# Moving around:

    bindsym $mod+$left focus left
    bindsym $mod+$down focus down
    bindsym $mod+$up focus up
    bindsym $mod+$right focus right
    
    bindsym $mod+Left focus left
    bindsym $mod+Down focus down
    bindsym $mod+Up focus up
    bindsym $mod+Right focus right

    bindsym $mod+Shift+$left move left
    bindsym $mod+Shift+$down move down
    bindsym $mod+Shift+$up move up
    bindsym $mod+Shift+$right move right
    bindsym $mod+Shift+Left move left
    
    bindsym $mod+Shift+Down move down
    bindsym $mod+Shift+Up move up
    bindsym $mod+Shift+Right move right

# Workspaces:

    bindsym $mod+1 workspace number 1
    bindsym $mod+2 workspace number 2
    bindsym $mod+3 workspace number 3
    bindsym $mod+4 workspace number 4
    bindsym $mod+5 workspace number 5
    bindsym $mod+6 workspace number 6
    bindsym $mod+7 workspace number 7
    bindsym $mod+8 workspace number 8
    bindsym $mod+9 workspace number 9
    bindsym $mod+0 workspace number 10

    bindsym $mod+Shift+1 move container to workspace number 1
    bindsym $mod+Shift+2 move container to workspace number 2
    bindsym $mod+Shift+3 move container to workspace number 3
    bindsym $mod+Shift+4 move container to workspace number 4
    bindsym $mod+Shift+5 move container to workspace number 5
    bindsym $mod+Shift+6 move container to workspace number 6
    bindsym $mod+Shift+7 move container to workspace number 7
    bindsym $mod+Shift+8 move container to workspace number 8
    bindsym $mod+Shift+9 move container to workspace number 9
    bindsym $mod+Shift+0 move container to workspace number 10

# Layout stuff:

    bindsym $mod+b splith
    bindsym $mod+v splitv
    bindsym $mod+e layout toggle split
    bindsym $mod+f fullscreen
    bindsym $mod+Shift+space floating toggle
    bindsym $mod+space focus mode_toggle
    bindsym $mod+a focus parent

# Scratchpad:

    bindsym $mod+Shift+minus move scratchpad
    bindsym $mod+minus scratchpad show

# Resizing containers:

mode "resize" {
    bindsym $left resize shrink width 10px
    bindsym $down resize grow height 10px
    bindsym $up resize shrink height 10px
    bindsym $right resize grow width 10px

    bindsym Left resize shrink width 10px
    bindsym Down resize grow height 10px
    bindsym Up resize shrink height 10px
    bindsym Right resize grow width 10px

    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym $mod+r mode "default"
}

mode "command" {
    # start mirroring
    bindsym n mode "default"; exec "wl-present mirror && wl-present fullscreen"
    # these commands modify an already running mirroring window
    # bindsym o mode "default"; exec wl-present set-output
    # bindsym r mode "default"; exec wl-present set-region
    # bindsym Shift+r mode "default"; exec wl-present unset-region
    # bindsym s mode "default"; exec wl-present set-scaling
    # bindsym f mode "default"; exec wl-present toggle-freeze
    # bindsym c mode "default"; exec wl-present custom

    # return to default mode
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+p mode "command"
bindsym $mod+r mode "resize"

# Cursor size 
seat seat0 xcursor_theme Adwaita 24
# waybar
bar swaybar_command waybar
# mouse warps to window in focus
mouse_warping container
# make (most) windows transparent
exec_always $HOME/.config/scripts/transcript/run.py
exec protonvpn-app
# sleep!
exec_always swayidle -w \
     timeout 300 'swaylock -f -c 000000' \
     timeout 400 'swaymsg "output * dpms off"' \
          resume 'swaymsg "output * dpms on"' \
     before-sleep 'swaylock -f -c 000000'
# sway snippets
include /etc/sway/config.d/*
